### PR TITLE
LDAP Enumeration and Add Computer Modules

### PR DESCRIPTION
**Pull request by Cyb3rC3lt**
As requested, moving my PR to the new Repo. Modules within are:

GROUP-MEM - Used to enumerate Groups within AD and return all their users or computers
COMP-DESC - Used to enumerate Computer accounts by any description text provided
ADD-COMPUTER - A port of Impackets addcomputer.py to CME

Further details and screenshots can be found here:
https://github.com/Cyb3rC3lt/CrackMapExec-Modules

### CODE REVIEW

**Comment by NeffIsBack** [comment]
@mpgn shall we merge it?

What about the requirements file, shall we purge that first?

**Comment by mpgn** [comment]
Hello @Cyb3rC3lt I will look into it tomorrow :)

**Comment by Cyb3rC3lt** [comment]
> Hello @Cyb3rC3lt I will look into it tomorrow :)

No problem at all. The add_computer one is the hardest to test for me as I only have one test domain at home. It worked on two clients so I'll be interested to see how your tests go.

GROUP-MEM seems to work well. I use it on every test to get DAs and DCs and has never failed. 

I've used COMP-DESC recently to find the Azure Sync box searching for text 'Azure' but I've used that one the least so far. Thanks

**Review by mpgn — COMMENTED** [review]
Can you remove the modification of the file requirements.txt ?

**Comment by Cyb3rC3lt** [comment]
Weirdly I didn't even touch this file. I think it's because my original PR was on the other Repo. I didn't check out a new branch but moved mine across so the requirements file was different to the mpgn branch. If you look now my requirements file is identical to the mpgn one

**Comment by Cyb3rC3lt** [comment]
Closing and moving here to fix sync issues: https://github.com/mpgn/CrackMapExec/pull/37

**Pull request closed without merging**
