### PR TITLE
Update connection.py to force FQDN

### PR DESCRIPTION
**Pull request by mpgn**
image

this PR fix https://github.com/mpgn/CrackMapExec/pull/24

### CODE REVIEW

**Comment by NeffIsBack** [comment]
LGTM👍🏼

Just fyi: the login function won’t execute then if any domain is bad specified (because len(username)!=len(password)

**Review by NeffIsBack — APPROVED** [review]

**Comment by mpgn** [comment]
Do you have an exemple ?

**Comment by NeffIsBack** [comment]
If you do something like `cme smb 10.0.0.1 -u user1\\domain.local user2\\sub.domain.local user3\\local -p password1 password2 password3 --no-bruteforce` it will accept user 1&2 and throw an error on user 3 so it is not in the user list. Than in line [394](https://github.com/mpgn/CrackMapExec/blob/ab692c5b9e25c6301a82d1570825099d33b3a384/cme/connection.py#L394C37-L394C43) it will stop the execution because there are 2 users and 3 passwords.

I think that makes sense because not every user is correctly specified but that's something we should keep in mind

**Comment by NeffIsBack** [comment]
> If you do something like `cme smb 10.0.0.1 -u user1\\domain.local user2\\sub.domain.local user3\\local -p password1 password2 password3 --no-bruteforce` it will accept user 1&2 and throw an error on user 3 so it is not in the user list. Than in line [394](https://github.com/mpgn/CrackMapExec/blob/ab692c5b9e25c6301a82d1570825099d33b3a384/cme/connection.py#L394C37-L394C43) it will stop the execution because there are 2 users and 3 passwords.
> 
> I think that makes sense because not every user is correctly specified but that's something we should keep in mind

bruteforcing won't be bothered by this though, it will just do users*passwords

**Comment by mpgn** [comment]
I can reproduce, it is expected for me and i'm glad the check if there, all good for you ?

image

**Comment by NeffIsBack** [comment]
> I can reproduce, it is expected for me and i'm glad the check if there, all good for you ?
> 
> image

Perfect 👍 LGTM

**Pull request merged**
