### PR TITLE
Update enum_av.py -- Bitdefender Endpoint

### PR DESCRIPTION
**Pull request by bongobongoland**
**"name": "\\bdConnector\\ServiceControl\\EPSecurityService.exe",**

^^^ I hope there are no syntax errors :)

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Looks good to me

**Review by mpgn — APPROVED** [review]

**Comment by mpgn** [comment]
Do you have a twitter handle @bongobongoland  ?

**Comment by bongobongoland** [comment]
> Do you have a twitter handle @bongobongoland ?

I don't use twitter (X). Should I?

**Comment by mpgn** [comment]
Aha no problemo, send me your postal adress on my email mpgn[at]protonmail.com to get a cme coin :)

**Pull request merged**
