### PR TITLE
Continue module run if one module fail #108 

### PR DESCRIPTION
**Pull request by mpgn**
Partial fix for Issue #108 

image

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Oh yes same thought, but let's print the stacktrace with debug so we can get an information about the module which is crashing.

Maybe `logger.debug(traceback.format_exc())`?

**Comment by NeffIsBack** [comment]
And maybe a short fail message to indicate which module wasn't loaded?

**Comment by mpgn** [comment]
You cannot get the name of the module since it is failing to load ^^

**Comment by NeffIsBack** [comment]
But we know the path it's trying to load :D

**Comment by mpgn** [comment]
the path is already printed, check the first line :)

**Comment by mpgn** [comment]
image

**Comment by NeffIsBack** [comment]
Fair enough, guess I am blind. Is there something useful in the stacktrace tho, what we could output as debug message?

**Comment by mpgn** [comment]
> Fair enough, guess I am blind. Is there something useful in the stacktrace tho, what we could output as debug message?

check last screenshot :)

**Review by NeffIsBack — APPROVED** [review]
Perfect, LGTM 👍🏼

**Pull request merged**
