### PR TITLE
[rdp] Add missing port variable & bug fixed

### PR DESCRIPTION
**Pull request by XiaoliChan**
Fix1: Add missing port variable
image

Fix2: Sometimes getting host info will fail.
- Traceback
image

### CODE REVIEW

**Comment by mpgn** [comment]
Hello,

can you past the full stacktrace for the fix2 ? maybe there is an issue with aardwolf

**Comment by XiaoliChan** [comment]
> Hello,
> 
> can you past the full stacktrace for the fix2 ? maybe there is an issue with aardwolf

Sure, all traceback is here:
[traceback.txt](https://github.com/mpgn/CrackMapExec/files/12329835/traceback.txt)

**Comment by NeffIsBack** [comment]
> > Hello,
> > can you past the full stacktrace for the fix2 ? maybe there is an issue with aardwolf
> 
> Sure, all traceback is here: [traceback.txt](https://github.com/mpgn/CrackMapExec/files/12329835/traceback.txt)

```
[23:39:20] ERROR    Exception while calling proto_flow() on target 10.2.16.93: 'NoneType' object has no attribute 'TargetInfo'                                                                                               connection.py:85
                    ╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/protocols/rdp.py:122 in create_conn_obj                                                                                 │                 
                    │                                                                                                                                                                                                      │                 
                    │   119 │   │   │   │   │   target=self.target,                                                                                                                                                        │                 
                    │   120 │   │   │   │   │   credentials=self.auth,                                                                                                                                                     │                 
                    │   121 │   │   │   │   )                                                                                                                                                                              │                 
                    │ ❱ 122 │   │   │   │   asyncio.run(self.connect_rdp())                                                                                                                                                │                 
                    │   123 │   │   │   except OSError as e:                                                                                                                                                               │                 
                    │   124 │   │   │   │   if "Errno 104" not in str(e):                                                                                                                                                  │                 
                    │   125 │   │   │   │   │   return False                                                                                                                                                               │                 
                    │                                                                                                                                                                                                      │                 
                    │ /usr/lib/python3.11/asyncio/runners.py:190 in run                                                                                                                                                    │                 
                    │                                                                                                                                                                                                      │                 
                    │   187 │   │   │   "asyncio.run() cannot be called from a running event loop")                                                                                                                        │                 
                    │   188 │                                                                                                                                                                                              │                 
                    │   189 │   with Runner(debug=debug) as runner:                                                                                                                                                        │                 
                    │ ❱ 190 │   │   return runner.run(main)                                                                                                                                                                │                 
                    │   191                                                                                                                                                                                                │                 
                    │   192                                                                                                                                                                                                │                 
                    │   193 def _cancel_all_tasks(loop):                                                                                                                                                                   │                 
                    │                                                                                                                                                                                                      │                 
                    │ /usr/lib/python3.11/asyncio/runners.py:118 in run                                                                                                                                                    │                 
                    │                                                                                                                                                                                                      │                 
                    │   115 │   │                                                                                                                                                                                          │                 
                    │   116 │   │   self._interrupt_count = 0                                                                                                                                                              │                 
                    │   117 │   │   try:                                                                                                                                                                                   │                 
                    │ ❱ 118 │   │   │   return self._loop.run_until_complete(task)                                                                                                                                         │                 
                    │   119 │   │   except exceptions.CancelledError:                                                                                                                                                      │                 
                    │   120 │   │   │   if self._interrupt_count > 0:                                                                                                                                                      │                 
                    │   121 │   │   │   │   uncancel = getattr(task, "uncancel", None)                                                                                                                                     │                 
                    │                                                                                                                                                                                                      │                 
                    │ /usr/lib/python3.11/asyncio/base_events.py:653 in run_until_complete                                                                                                                                 │                 
                    │                                                                                                                                                                                                      │                 
                    │    650 │   │   if not future.done():                                                                                                                                                                 │                 
                    │    651 │   │   │   raise RuntimeError('Event loop stopped before Future completed.')                                                                                                                 │                 
                    │    652 │   │                                                                                                                                                                                         │                 
                    │ ❱  653 │   │   return future.result()                                                                                                                                                                │                 
                    │    654 │                                                                                                                                                                                             │                 
                    │    655 │   def stop(self):                                                                                                                                                                           │                 
                    │    656 │   │   """Stop running the event loop.                                                                                                                                                       │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/protocols/rdp.py:174 in connect_rdp                                                                                     │                 
                    │                                                                                                                                                                                                      │                 
                    │   171 │   async def connect_rdp(self):                                                                                                                                                               │                 
                    │   172 │   │   _, err = await self.conn.connect()                                                                                                                                                     │                 
                    │   173 │   │   if err is not None:                                                                                                                                                                    │                 
                    │ ❱ 174 │   │   │   raise err                                                                                                                                                                          │                 
                    │   175 │                                                                                                                                                                                              │                 
                    │   176 │   def kerberos_login(self, domain, username, password="", ntlm_hash="", aesKey="",                                                                                                           │                 
                    │       kdcHost="", useCache=False):                                                                                                                                                                   │                 
                    │   177 │   │   try:                                                                                                                                                                                   │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/aardwolf/connection.py:266 in connect                                                                                       │                 
                    │                                                                                                                                                                                                      │                 
                    │    263 │   │   │   │   if SUPP_PROTOCOLS.HYBRID in self.x224_protocol or                                                                                                                             │                 
                    │        SUPP_PROTOCOLS.HYBRID_EX in self.x224_protocol:                                                                                                                                               │                 
                    │    264 │   │   │   │   │   _, err = await self.credssp_auth()                                                                                                                                        │                 
                    │    265 │   │   │   │   │   if err is not None:                                                                                                                                                       │                 
                    │ ❱  266 │   │   │   │   │   │   raise err                                                                                                                                                             │                 
                    │    267 │   │   │   │   │                                                                                                                                                                             │                 
                    │    268 │   │   │   │   │   #switching back to tpkt                                                                                                                                                   │                 
                    │    269 │   │   │   │   │   self.__connection.change_packetizer(TPKTPacketizer())                                                                                                                     │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/aardwolf/connection.py:369 in credssp_auth                                                                                  │                 
                    │                                                                                                                                                                                                      │                 
                    │    366 │   │   │   │   token = await self.__connection.read_one()                                                                                                                                    │                 
                    │    367 │   │   │   │   data, to_continue, err = await self.authapi.authenticate(token, flags =                                                                                                       │                 
                    │        None, certificate = certificate, spn=self.target.to_target_string())                                                                                                                          │                 
                    │    368 │   │   │   │   if err is not None:                                                                                                                                                           │                 
                    │ ❱  369 │   │   │   │   │   raise err                                                                                                                                                                 │                 
                    │    370 │   │   │   │                                                                                                                                                                                 │                 
                    │    371 │   │   │   │   if to_continue is False:                                                                                                                                                      │                 
                    │    372 │   │   │   │   │   # credSSP auth finished, flushing remaining data                                                                                                                          │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/credssp/client/native.py:45 in authenticate                                                               │                 
                    │                                                                                                                                                                                                      │                 
                    │    42 │   │   │                                                                                                                                                                                      │                 
                    │    43 │   │   │   if token is None:                                                                                                                                                                  │                 
                    │    44 │   │   │   │   # initial auth                                                                                                                                                                 │                 
                    │ ❱  45 │   │   │   │   returndata, self.__internal_auth_continue, err = await                                                                                                                         │                 
                    │       self.auth_ctx.authenticate(token, flags = flags, spn = spn)                                                                                                                                    │                 
                    │    46 │   │   │   │   if err is not None:                                                                                                                                                            │                 
                    │    47 │   │   │   │   │   raise err                                                                                                                                                                  │                 
                    │    48                                                                                                                                                                                                │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/spnego/client/native.py:216 in authenticate                                                               │                 
                    │                                                                                                                                                                                                      │                 
                    │   213 │   │                                                                                                                                                                                          │                 
                    │   214 │   │   else:                                                                                                                                                                                  │                 
                    │   215 │   │   │   #everything is netotiated, but authentication needs more setps                                                                                                                     │                 
                    │ ❱ 216 │   │   │   neg_token_raw = NegotiationToken.load(token)                                                                                                                                       │                 
                    │   217 │   │   │   neg_token = neg_token_raw.native                                                                                                                                                   │                 
                    │   218 │   │   │   if neg_token['negState'] == 'accept-completed':                                                                                                                                    │                 
                    │   219 │   │   │   │   return None, False, None                                                                                                                                                       │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asn1crypto/core.py:1062 in load                                                                                             │                 
                    │                                                                                                                                                                                                      │                 
                    │   1059 │   │   """                                                                                                                                                                                   │                 
                    │   1060 │   │                                                                                                                                                                                         │                 
                    │   1061 │   │   if not isinstance(encoded_data, byte_cls):                                                                                                                                            │                 
                    │ ❱ 1062 │   │   │   raise TypeError('encoded_data must be a byte string, not %s' %                                                                                                                    │                 
                    │        type_name(encoded_data))                                                                                                                                                                      │                 
                    │   1063 │   │                                                                                                                                                                                         │                 
                    │   1064 │   │   value, _ = _parse_build(encoded_data, spec=cls, spec_params=kwargs,                                                                                                                   │                 
                    │        strict=strict)                                                                                                                                                                                │                 
                    │   1065 │   │   return value                                                                                                                                                                          │                 
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                    TypeError: encoded_data must be a byte string, not NoneType                                                                                                                                                              
                                                                                                                                                                                                                                             
                    During handling of the above exception, another exception occurred:                                                                                                                                                      
                                                                                                                                                                                                                                             
                    ╭───────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────────────────────────────────────────────╮                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:83 in __init__                                                                                            │                 
                    │                                                                                                                                                                                                      │                 
                    │    80 │   │   │   sleep(value)                                                                                                                                                                       │                 
                    │    81 │   │                                                                                                                                                                                          │                 
                    │    82 │   │   try:                                                                                                                                                                                   │                 
                    │ ❱  83 │   │   │   self.proto_flow()                                                                                                                                                                  │                 
                    │    84 │   │   except Exception as e:                                                                                                                                                                 │                 
                    │    85 │   │   │   self.logger.exception(f"Exception while calling proto_flow() on target                                                                                                             │                 
                    │       {self.host}: {e}")                                                                                                                                                                             │                 
                    │    86                                                                                                                                                                                                │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/connection.py:127 in proto_flow                                                                                         │                 
                    │                                                                                                                                                                                                      │                 
                    │   124 │   def proto_flow(self):                                                                                                                                                                      │                 
                    │   125 │   │   self.logger.debug(f"Kicking off proto_flow")                                                                                                                                           │                 
                    │   126 │   │   self.proto_logger()                                                                                                                                                                    │                 
                    │ ❱ 127 │   │   if self.create_conn_obj():                                                                                                                                                             │                 
                    │   128 │   │   │   self.enum_host_info()                                                                                                                                                              │                 
                    │   129 │   │   │   if self.print_host_info():                                                                                                                                                         │                 
                    │   130 │   │   │   │   # because of null session                                                                                                                                                      │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/cme/protocols/rdp.py:130 in create_conn_obj                                                                                 │                 
                    │                                                                                                                                                                                                      │                 
                    │   127 │   │   │   │   if "TCPSocket" in str(e):                                                                                                                                                      │                 
                    │   128 │   │   │   │   │   return False                                                                                                                                                               │                 
                    │   129 │   │   │   │   if "Reason:" not in str(e):                                                                                                                                                    │                 
                    │ ❱ 130 │   │   │   │   │   info_domain = self.conn.get_extra_info()                                                                                                                                   │                 
                    │   131 │   │   │   │   │   self.domain = info_domain["dnsdomainname"]                                                                                                                                 │                 
                    │   132 │   │   │   │   │   self.hostname = info_domain["computername"]                                                                                                                                │                 
                    │   133 │   │   │   │   │   self.server_os = info_domain["os_guess"] + " Build " +                                                                                                                     │                 
                    │       str(info_domain["os_build"])                                                                                                                                                                   │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/aardwolf/connection.py:337 in get_extra_info                                                                                │                 
                    │                                                                                                                                                                                                      │                 
                    │    334 │                                                                                                                                                                                             │                 
                    │    335 │   def get_extra_info(self):                                                                                                                                                                 │                 
                    │    336 │   │   # for NTLM fingerprinting                                                                                                                                                             │                 
                    │ ❱  337 │   │   ntlm_data = self.authapi.get_extra_info()                                                                                                                                             │                 
                    │    338 │   │   if ntlm_data is not None:                                                                                                                                                             │                 
                    │    339 │   │   │   return ntlm_data.to_dict()                                                                                                                                                        │                 
                    │    340 │   │   return None                                                                                                                                                                           │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/credssp/client/native.py:31 in get_extra_info                                                             │                 
                    │                                                                                                                                                                                                      │                 
                    │    28 │   │   return                                                                                                                                                                                 │                 
                    │       cert['tbs_certificate']['subject_public_key_info']['public_key'].dump()[5:] #why?                                                                                                              │                 
                    │    29 │                                                                                                                                                                                              │                 
                    │    30 │   def get_extra_info(self):                                                                                                                                                                  │                 
                    │ ❱  31 │   │   return self.auth_ctx.get_extra_info()                                                                                                                                                  │                 
                    │    32 │                                                                                                                                                                                              │                 
                    │    33 │   def get_active_credential(self):                                                                                                                                                           │                 
                    │    34 │   │   return self.auth_ctx.get_active_credential()                                                                                                                                           │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/spnego/client/native.py:137 in get_extra_info                                                             │                 
                    │                                                                                                                                                                                                      │                 
                    │   134 │                                                                                                                                                                                              │                 
                    │   135 │   def get_extra_info(self):                                                                                                                                                                  │                 
                    │   136 │   │   if hasattr(self.selected_authentication_context, 'get_extra_info'):                                                                                                                    │                 
                    │ ❱ 137 │   │   │   return self.selected_authentication_context.get_extra_info()                                                                                                                       │                 
                    │   138 │   │   return None                                                                                                                                                                            │                 
                    │   139 │                                                                                                                                                                                              │                 
                    │   140 │   def get_session_key(self):                                                                                                                                                                 │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/ntlm/client/native.py:96 in get_extra_info                                                                │                 
                    │                                                                                                                                                                                                      │                 
                    │    93 │   │   return NegotiateFlags.NEGOTIATE_EXTENDED_SESSIONSECURITY in                                                                                                                            │                 
                    │       self.ntlmChallenge.NegotiateFlags                                                                                                                                                              │                 
                    │    94 │                                                                                                                                                                                              │                 
                    │    95 │   def get_extra_info(self):                                                                                                                                                                  │                 
                    │ ❱  96 │   │   self.extra_info = NTLMServerInfo.from_challenge(self.ntlmChallenge)                                                                                                                    │                 
                    │    97 │   │   return self.extra_info                                                                                                                                                                 │                 
                    │    98 │                                                                                                                                                                                              │                 
                    │    99 │   def MAC(self, handle, signingKey, seqNum, message):                                                                                                                                        │                 
                    │                                                                                                                                                                                                      │                 
                    │ /home/xiaoli/.local/pipx/venvs/crackmapexec/lib/python3.11/site-packages/asyauth/protocols/ntlm/structures/serverinfo.py:67 in from_challenge                                                        │                 
                    │                                                                                                                                                                                                      │                 
                    │    64 │   @staticmethod                                                                                                                                                                              │                 
                    │    65 │   def from_challenge(challenge):                                                                                                                                                             │                 
                    │    66 │   │   si = NTLMServerInfo()                                                                                                                                                                  │                 
                    │ ❱  67 │   │   ti = challenge.TargetInfo                                                                                                                                                              │                 
                    │    68 │   │   for k in ti:                                                                                                                                                                           │                 
                    │    69 │   │   │   if k == AVPAIRType.MsvAvNbDomainName:                                                                                                                                              │                 
                    │    70 │   │   │   │   si.domainname = ti[k]                                                                                                                                                          │                 
                    ╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯                 
                    AttributeError: 'NoneType' object has no attribute 'TargetInfo'                                                                                                                                                          

```

**Review by mpgn — APPROVED** [review]

**Comment by mpgn** [comment]
if the exception is raised

image

**Review by NeffIsBack — APPROVED** [review]
LGTM 👍

**Pull request merged**
