### PR TITLE
Add audit mode and reveal X pwd chars to RDP protocol

### PR DESCRIPTION
**Pull request by Kahvi-0**
Add audit mode and reveal X pwd chars to RDP protocol.

Without audit mode:
image
image

With audit mode:
image

image

### CODE REVIEW

**Comment by NeffIsBack** [comment]
Thanks for pointing out, that audit mode does not work with the rdp protocol yet! Tho there is already a function for this behaviour. Just import `process_secret` from the config.py file, wrap the secrets in the rdp file with it and we are good to go

**Comment by Kahvi-0** [comment]
Changed :) Thanks for pointing this out. I noticed that winrm also has not adopted audit mode so I will add it while I am at it.

**Review by NeffIsBack — APPROVED** [review]
Great 👍 LGTM

**Review by mpgn — CHANGES_REQUESTED** [review]
Nice PR, you missed the function kerberos_login() :)

**Comment by Kahvi-0** [comment]
My bad, should be good now :p

**Review by NeffIsBack — APPROVED** [review]
LGTM👍🏼

**Review by mpgn — APPROVED** [review]

**Pull request merged**
