### PR TITLE
New module pi 

### PR DESCRIPTION
**Pull request by termanix**
Pi module is used to run commands by process injection method for logged in user(s) in case of having admin rights on windows system.

### CODE REVIEW

**Comment by termanix** [comment]
image

**Comment by mpgn** [comment]
Can you link the location of the code compiled ?

**Comment by termanix** [comment]
Sure, i uploaded now. Here it is
https://github.com/termanix/RunCommandViaProcessInjection

**Comment by mpgn** [comment]
Is there a diff between this one and the impersonate module ?

**Comment by termanix** [comment]
Yes there is a difference. impersonate module uses token impersonation. Taking the token of target user and creating process with target users token. My tool is using process injection method. Choosing a process and  execute specific commands on the hijacked process by having code run in the memory of a process.

**Comment by termanix** [comment]
Let me explain with screenshots. The target user "UserCA" is domain user in my test lab. When we try to run command with token impersonation we got access denied. Cause impersonate module cant start a process for target user because he has not enough permission. But we can run command for target user with process injection method.

image

**Comment by mpgn** [comment]
image

**Review by mpgn — APPROVED** [review]

**Pull request merged**
