### PR TITLE
Update impersonate.py

### PR DESCRIPTION
**Pull request by Dfte**
Update the impersonate module so that it prints token integrity :)

### CODE REVIEW

**Comment by mpgn** [comment]
Thanks <3

**Comment by Cyb3rC3lt** [comment]
Hi @Dfte, is this module definitely working on CME 6.0.1? I was trying to use it today without any luck but Metasploit could return delegation tokens via incognito as seen in the bottom screenshot. The exe also shows tokens.  I have no AV on and it is a standard Windows 10 machine.

image

ImpersonateExe

**Comment by Dfte** [comment]
Hey! Did you use the code from this PR ?

**Comment by Cyb3rC3lt** [comment]
Hey dfte, I didn't to be honest. CME just had an update to its smb code so not sure if that's relevant too. I will try the updated code from you today.

**Comment by Cyb3rC3lt** [comment]
Just confirmed with the latest smb code from CME and your latest code it is working now. Not sure which caused it but all good now :-)

image

**Comment by Dfte** [comment]
Niceeeeeeeeee! :D

**Comment by mpgn** [comment]
image

**Review by mpgn — APPROVED** [review]

**Comment by termanix** [comment]
Hello, i wrote the same things using token impersonation my code. It works the same as crakmapexec's impersonate module. After a lot testing I relized, if we have NT/Authority SYSTEM rights on host machine in AD, (talking about for Domain Admins) token impersonation works only Domain\Administrator accounts, not working for other Domain Admins accounts, also tried crackmap's impersonate module and impersonate.exe i got access denied both tool.  (or i couldnt do that). Cause other DA accounts is not coming with seimpersonate or sedebug privileges on default, needs to run as admin for privileges. In real life testing there are so many DA accouns logged in host machines. I  used process injection to run command for other DA accounts. I want to talk about this and i want to contribute for this module.

**Comment by mpgn** [comment]
Hello @termanix go check the source code directly one https://github.com/sensepost/impersonate :)

**Pull request merged**
