### PR TITLE
Enhanced the comp-desc module

### PR DESCRIPTION
**Pull request by Cyb3rC3lt**
Hi guys,

I have been using the comp-desc module today and although it is great for lots of scenarios there was a time I wanted to return all the machines that were SQL servers.

Currently with the module if you put in SQL as the search term it won't find any as it only looks in the "operating system" attribute in AD so it can only return results like "server" or "xp". I wanted to enhance it to also look at the name of the servers so any servers called 'ACME-SQL01' and 'ACME-SQL02' will now be returned if you put SQL as your search term.

I think it makes it more powerful but see what you think.

Thanks
David

### CODE REVIEW

**Comment by NeffIsBack** [comment]
I think thats way more powerful as you can properly search now. But it should be renamed, maybe something like `comp-search` or `find-pc`

**Comment by mpgn** [comment]
I agree we could rename the module to be more explicit

**Comment by Cyb3rC3lt** [comment]
Yeah agreed, a rename would make sense. Given we have an add-computer module I thought to rename it find-computer to have some sort of uniformity. I changed the DESC field to TEXT too so to run it just do:

`cme ldap $IP -u 'user' -p 'pass' -d test.local -M find-computer -o TEXT=DC`

**Review by mpgn — APPROVED** [review]

**Comment by NeffIsBack** [comment]
Should we merge?

**Pull request merged**
