### PR TITLE
[smb] RDP Module: improve try catch

### PR DESCRIPTION
**Pull request by XiaoliChan**
Sometimes, the dcom firewall is blocked and will raise an exception(not hanging), the exception code is `0x800706ba`, so need to try the whole `dcom initial` function.

issue ticket: #125 

Reference:
- https://github.com/fortra/impacket/pull/1088

### CODE REVIEW

**Comment by XiaoliChan** [comment]
@bongobongoland Can you try this PR?

**Comment by bongobongoland** [comment]
Do I need to enable the firewall first? :)

**Comment by XiaoliChan** [comment]
> Do I need to enable the firewall first? :)

Sure, make it raise exception.

**Comment by XiaoliChan** [comment]
@bongobongoland Any feedback?

**Comment by bongobongoland** [comment]
I can't make it show the error :)
I have enabled the firewall but that didn't do the trick.

**Comment by XiaoliChan** [comment]
> I can't make it show the error :) I have enabled the firewall but that didn't do the trick.

You means the error is gone? you can try `-M rdp -o METHOD=wmi`

**Comment by bongobongoland** [comment]
Do I need to remove something from the firewall rules?

**Comment by XiaoliChan** [comment]
> Do I need to remove something from the firewall rules?

No, just make it enabled, I need to test will the CME raise an exception again.

**Comment by bongobongoland** [comment]
Your PR works fine. But current rdp.py works fine as well. Because even though I have enabled the firewall, I can't replicate the original error. :\

**Comment by XiaoliChan** [comment]
> Your PR works fine. But current rdp.py works fine as well. Because even though I have enabled the firewall, I can't replicate the original error. :\

OK, the module will not raise the exception in an ugly way after this PR.

**Review by mpgn — APPROVED** [review]

**Review by NeffIsBack — APPROVED** [review]
LGTM 👍

**Comment by XiaoliChan** [comment]
My fault, This PR is combine in #129

**Pull request closed without merging**
