### PR TITLE
Extract credentials in IIS Application Pool configuration files

### PR DESCRIPTION
**Pull request by Shad0wC0ntr0ller**
Checks for credentials in IIS Application Pool configuration files using appcmd.exe

IIS application pools can run as different users for security and isolation reasons. When you specify a user for the application pool there credentials are saved in plaintext in the configuration file. 

image

### CODE REVIEW

**Comment by Shad0wC0ntr0ller** [comment]
Just checking in to see if anything needs to be done on my end. Thank you

**Comment by mpgn** [comment]
Hello @Shad0wC0ntr0ller I did my review of your PR :)
image

**Comment by Shad0wC0ntr0ller** [comment]
I have removed the on_login method, as well as added the APPPOOL.NAME to be printed along with the found credentials.

image

**Comment by mpgn** [comment]
All good for me, what about renaming the module "iis" instead of "appcmd" ?

**Review by mpgn — APPROVED** [review]

**Comment by Shad0wC0ntr0ller** [comment]
Sounds great, I have also updated the name from appcmd to iis

**Review by mpgn — APPROVED** [review]

**Comment by NeffIsBack** [comment]
@Shad0wC0ntr0ller Review done as well. If that's changed i think we are ready to merge
image

**Comment by NeffIsBack** [comment]
Did you test with passwords that only contain empty spaces? Recently there was an issue with the veeam module where it crashed in exactly that scenario (#72). Not sure if this is the case here but the code looks like it could have the same issue

**Comment by Shad0wC0ntr0ller** [comment]
@NeffIsBack I just replaced context.log.error with context.log.fail
I will also take a look at #72 and see if this module has the same error, please give me an hour at most

**Comment by Shad0wC0ntr0ller** [comment]
Ok i have now added the option to print a user with no password if found, the only issue im having is using the context.log.fail
gives this error "Error while loading module <CMEModule.CMEModule object at 0x7fdc2f626110>: 'CMEAdapter' object has no attribute 'fail'"

Should i change it back to error ?

image

**Comment by NeffIsBack** [comment]
This is very odd. `.fail()` should look exactly `.error()` in your screenshot (And Error more like this), this was changed many versions ago. Can you give me your cme version? Did you install cme using pipx?

image

From you appcmd.py file:
image

**Comment by Shad0wC0ntr0ller** [comment]
@NeffIsBack Yes i installed crackmapexec with pipx, but i dont remember if im working with the sponsored version or not, its has been a minute since install, let me remove everything and get the latest version and report back in a min

**Comment by Shad0wC0ntr0ller** [comment]
@NeffIsBack Yea i was on 5.4.6 lol , updating to 6.0.1 context.log.fail is working as expected

image

**Comment by NeffIsBack** [comment]
> @NeffIsBack Yea i was on 5.4.6 lol , updating to 6.0.1 context.log.fail is working as expected

Perfect 👍

**Review by NeffIsBack — APPROVED** [review]
Rest looks good to me 👍 Thanks for the nice PR

**Review by mpgn — APPROVED** [review]

**Pull request merged**
